### PR TITLE
Feature/job system

### PR DESCRIPTION
**Pull request by stefan520**
Adding a very early job system. I will continue working on it.

### CODE REVIEW

**Comment by EuroBlue** [comment]
GetJobs()
GetJob( int index )
Why are dose functions needed?

**Comment by EuroBlue** [comment]
And should Job Groups/Tags be implemented here or later

**Comment by IRLadderGoat** [comment]
Preferrebly there'd be a game resource or an enum describing the different job groups/tags

**Comment by stefan520** [comment]
@EuroBlue Ex. when we need to give the players weapons for the job or kill player before switching job when we get that setting.
I will take groups after this. Now we got something. I will just merge so I dont get to much behind upstream. :)

**Comment by stefan520** [comment]
@IRLadderGoat Hmm I am not sure, what you are trying to tell me. I am still new in game development, but have alot experience in software.

**Comment by IRLadderGoat** [comment]
Game Resources are the S&Box way of handling custom assets that are data based. These custom assets can be loaded in when needed, which would mean that at some point, the people hosting servers can just place job file descriptions in a file and it will be loaded in the next time the game starts.

Here is the, somewhat lacking, documentation for custom assets:
https://wiki.facepunch.com/sbox/Custom_Asset_Types

Here is an example of an custom asset and it's definition in another project:
https://github.com/Facepunch/sbox-hc1/blob/main/Assets/radio_sounds/terrorist.radio
https://github.com/Facepunch/sbox-hc1/blob/main/Code/GameMode/Audio/RadioSounds.cs

**Comment by IRLadderGoat** [comment]
As a continuation, you've created a nice design but it just needs a little bit to be perfect.

**Comment by stefan520** [comment]
We can do that yes, but @sousou63 did not want to create jobs with files like that.
We like it the classic way added all the jobs in the same file.

**Comment by IRLadderGoat** [comment]
Independently of what the earlier game did, it would be preferable for users to be able to add either one file among other configuration files or more files in a folder specifically for jobs. Either way the jobs should definitely be defined in data files and not in the code

**Comment by IRLadderGoat** [comment]
I'm also sure there is some workaround to placing all jobs in one folder as it is just json

**Comment by stefan520** [comment]
Okay, I will the job manging file to the data folder.
A JSON file would not be a option because it's far from user friendly. Opens up for too many errors when everything is free text.
I will move this discussion to the discord server.

**Comment by sousou63** [comment]
Idk about custom asset types, seems like it's very related to the editor and not the user which will need to make modifications directly with config files, maybe I'm just misunderstanding the system tho.

**Comment by IRLadderGoat** [comment]
The documentation specifies that the game resources are hotloaded when in game, meaning that they will be, with high certainty, available for modification with the shipped game. I.e. allowing for people hosting to modify according to what they want at anytime, not just in the editor. 

In anyway, it is possible to test the theory by exporting the game whilst it has any type of customly defined assets

**Pull request merged**
