### PR TITLE
Data Persistence, saving and loading player data

### PR DESCRIPTION
**Pull request by EuroBlue**
Should work
Works on my machine
Log.Infos are usefull

### CODE REVIEW

**Comment by QueenPM** [comment]
Could you give a brief description of how it works?

With examples

**Comment by EuroBlue** [comment]
It creates a folder in the sbox data "playersdata"
There are json files of objects of the class SavedPlayer
SavedPlayer is a class that stores everything you want to store
When a new player is created it checks if there is file file in the playersdata folder with the steamid
If it exists it creates Insctance of SavedPlayer: loadedplayer
loads the data from loadedplayer to the actual Player GameObject

It updates the playerdata in the json file when the RemovePlayer function is called

**Comment by EuroBlue** [comment]
Right now it stores only money, but its very modular very demure, very commented, very mindful
So it's easy to expand on need

**Comment by QueenPM** [comment]
MoneyBase seems to be duplicated

**Comment by EuroBlue** [comment]
Yeah forgot to commit the merge fix now it's good

**Review by QueenPM — APPROVED** [review]
Looks good to me. Good starting point for data persistence.

**Review by sousou63 — APPROVED** [review]
Very good, thanks you

**Pull request merged**
