### PR TITLE
Fixed player collider, hands fix

### PR DESCRIPTION
**Pull request by Mangrogred**
- Fixed player collider: now you can't move props with your feet
- Hands fix: Now, when you sharply turn and release an object, it does not fly away at speed. Also increased throw strength

### CODE REVIEW

**Comment by QueenPM** [comment]
I kind of like moving props around with my fret

**Comment by Mangrogred** [comment]
> I kind of like moving props around with my fret

But I removed it because
1. It's not realistic
2. We have hands now
3. This didn’t happen in dark rp

**Comment by QueenPM** [comment]
It does happen in DarkRP. Your feet collide with props and they jitter around

**Comment by Mangrogred** [comment]
> It does happen in DarkRP. Your feet collide with props and they jitter around

In dark rp you moved the props just with your feet, but now you literally float on them
Maybe in future we add this

**Pull request closed without merging**
