### PR TITLE
Added basic LODs

### PR DESCRIPTION
**Pull request by goodmittens**
- LOD UVs need to be refined.
- Fan LOD needs to be added and setup.
- Also added Diamond skin as opposed to titanium.
- Basic Water cooler.

### CODE REVIEW

**Comment by goodmittens** [comment]
You can ignore changes to minimal of course

**Comment by goodmittens** [comment]
Removed printers I spawned in minimal. Adjusting LOD UVs.

**Comment by sousou63** [comment]
Oh my bad I tought it was finished so I fixed the conflict

**Comment by goodmittens** [comment]
It should be good enough now I think. I can return it later to touch it up more.

**Pull request merged**
