### PR TITLE
Door expansion

### PR DESCRIPTION
**Pull request by goodmittens**
Playing around with door hinges
Frame can be added into prefab, just need to rotate only the comp Prefab setup will feature modular doors with options for doors, frames, handles Lower frame toggle for setting up interior/exterior doors Multiple material setup for inter/exterior transitions Also not shown here is setup for double doors
Included tintable frame
Still WIP for scaling, minor details, and topo

### CODE REVIEW

**Comment by EuroBlue** [comment]
Do you plan to implement a system that makes doors map independent?

**Comment by goodmittens** [comment]
What do you mean by doors map? Not sure how functional it will be in terms of prefab, technically if prefabs are exposed this would be a setup for pcg. This is more for map artists to have modular pieces and options when setting up buildings. If you mean door material, yes it is currently independent with it's own (messy atm) UVs. The knob will also be separate for animation.

**Comment by goodmittens** [comment]
I would like to supply a few base materials options for all pieces over time.

**Comment by EuroBlue** [comment]
I mean make sure that doors are not needed to be hardcoded into a map. But can be used on any map.
Basicly make sure that the doors would not be a bigger hustle in s&box than they are in gmod

**Comment by goodmittens** [comment]
They already have the door prefab setup? This is swapping (actually just adding more) models and textures. The models included would be for instances of the prefab. The door prefab would then be included in a building prefab. All instances could be stored in an array for example if someone wanted to go that far. Which could be randomized or tagged to be used in certain buildings. Or they could simply lay out instances, it's up to whoever uses it

**Comment by goodmittens** [comment]
I thought draft PR was private tbh. Also I need to update minimal so I am going to grab a new branch and make it just double door and a few variations for now. I also will keep it off PR until they say they are ready, my bad!

**Pull request closed without merging**
